name: CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install frontend dependencies
      run: |
        cd client
        npm ci

    - name: Build frontend
      run: |
        cd client
        npm run build

    - name: Build frontend Docker image
      run: |
        cd client
        docker build -t ${{ env.DOCKER_USERNAME }}/f-codex:${{ env.GITHUB_SHA }} 

    - name: Install backend dependencies
      run: |
        cd server
        npm ci

    - name: Build backend Docker image
      run: |
        cd server
        docker build -t ${{ env.DOCKER_USERNAME }}/b-codex:${{ env.GITHUB_SHA }} 

    - name: Push frontend and backend Docker images to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push frontend Docker image
      uses: docker/push-action@v1
      with:
        tags: ${{ env.DOCKER_USERNAME }}/my-frontend-app:${{ env.GITHUB_SHA }}

    - name: Push backend Docker image
      uses: docker/push-action@v1
      with:
        tags: ${{ env.DOCKER_USERNAME }}/my-backend-app:${{ env.GITHUB_SHA }}
